name: yamatae_application
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^1.4.0
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  google_maps_flutter: ^2.1.3
  location: ^4.3.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts: 
    - family: Kotta One
      fonts: 
        - asset: assets/fonts/kottaoneregular400.ttf
          weight: 400
